cleaning hard_checkout
Signed-off-by: Stefano Fiorentino <stefano.fiorentino@adesso.ch>

diff --git a/git-hard_checkout b/git-hard_checkout
--- a/git-hard_checkout
+++ b/git-hard_checkout
@@ -3,8 +3,14 @@
 BRANCH_NAME="${1}"
 
 git stash && \
-    git fetch && \
-    git branch -d ${BRANCH_NAME} && \
-    git checkout -b ${BRANCH_NAME} origin/${BRANCH_NAME} && \
+    git remote update
+
+CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
+
+if [ "${CURRENT_BRANCH}" = "${BRANCH_NAME}" ]; then
     git reset --hard origin/${BRANCH_NAME} || (echo "ERROR: resetting to origin's HEAD"; exit 1)
-git pull --rebase origin ${BRANCH_NAME}
+else
+    git branch -d ${BRANCH_NAME} && \
+        git checkout -b ${BRANCH_NAME} origin/${BRANCH_NAME} && \
+        git reset --hard origin/${BRANCH_NAME} || (echo "ERROR: resetting to origin's HEAD"; exit 1)
+fi
