simplifying hard_checkout
Signed-off-by: Stefano Fiorentino <stefano.fiorentino@adesso.ch>

diff --git a/git-hard_checkout b/git-hard_checkout
--- a/git-hard_checkout
+++ b/git-hard_checkout
@@ -3,14 +3,6 @@
 BRANCH_NAME="${1}"
 
 git stash && \
-    git remote update
-
-CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
-
-if [ "${CURRENT_BRANCH}" = "${BRANCH_NAME}" ]; then
-    git reset --hard origin/${BRANCH_NAME} || (echo "ERROR: resetting to origin's HEAD"; exit 1)
-else
-    git branch -d ${BRANCH_NAME} && \
-        git checkout -b ${BRANCH_NAME} origin/${BRANCH_NAME} && \
-        git reset --hard origin/${BRANCH_NAME} || (echo "ERROR: resetting to origin's HEAD"; exit 1)
-fi
+    git remote update || (echo "ERROR: fetching and updating"; exit 1)
+git checkout ${BRANCH_NAME} || git checkout -b ${BRANCH_NAME} origin/${BRANCH_NAME}  || (echo "ERROR: checking out"; exit 1)
+git reset --hard origin/${BRANCH_NAME} || (echo "ERROR: resetting to origin's HEAD"; exit 1)
